spring.application.name=MyFitnessPal
# Database
spring.datasource.url=jdbc:mysql://localhost:3306/fitnessAppDb
spring.datasource.username=root
spring.datasource.password=ayushkr1901#

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect